namespace DirectoryManager.Data.Enums
{
    public enum SiteConfigSetting
    {
        Unknown = 0,
        HeaderHtml = 1,
        FooterHtml = 2,
        HomePageDisplayHtml = 3,
        PaymentCurrencyMessage = 4,
        HomePageMetaTags = 5,
        CssHeader = 6,
        DirectoryLegendHtml = 7,
        HomePageTitle = 8,
        DonationHtml = 9,
        NowPaymentsMessageHtml = 10,
        SubmissionGuidelinesHtml = 11,
        AzureStorageConnectionString = 12,
        CdnPrefixWithProtocol = 13,
        BlobPrefix = 14,
        Link2Name = 15,
        Link3Name = 16,
        ContactHtml = 17,
        SuccessPageHtml = 18,
        MainSponsoredListingDetails = 19,
        SiteName = 20,
        SubcategorySponsoredListingDetails = 21,
        TopBannerHtml = 22,
        FullRootUrl = 23,
        CanonicalDomain = 24,
        FullRootTorUrl = 25,
        TopMenuActionsHtml = 26,
        InvoiceSuccessMessageHtml = 27,
        EmailSettingUnsubscribeEmail = 28,
        EmailSettingUnsubscribeUrlFormat = 29,
        EmailSettingUnsubscribeFooterText = 30,
        EmailSettingUnsubscribeFooterHtml = 31,
        SendGridApiKey = 32,
        SendGridSenderEmail = 33,
        SendGridSenderName = 34,
        NewsletterSummaryHtml = 35,
        SiteLogoUrl = 36,
        CategorySponsoredListingDetails = 37,
        SponsoredListingSteps = 38,
        AppDomain = 39,
        TextIntro = 40,
        FAQHtml = 41,
        SearchBlacklistRedirectUrl = 42
    }
}